version: '3.7'
services:    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/certi.crt:/etc/nginx/certi.crt
      - ./nginx/certs/certi.key:/etc/nginx/certi.key
      - ./nginx/generated:/generated/
      - ./nginx/data:/www/data
    ports:
      - "80:80"
      - "443:443"