services:
  service1:
    image: nginx:latest
    ports:
    - service1nginx:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./data/:/www/data/:ro
  service2:
    image: nginx:latest
    ports:
    - service2nginx:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./data2/:/www/data/:ro
version: '3.8'
